name: CD to GKE (Docker Hub)

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI - DevSecOps TP2"]
    types:
      - completed


  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/myapp:leatest"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV


      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      # Install gcloud CLI (optional if runner already has it)
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: kubectl,gke-gcloud-auth-plugin


      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials tp3 --region europe-west9 --project ${{ secrets.PROJECT_ID }}

      - name: Update Deployment image
        run: |
          kubectl set image deployment/myapp-deployment \
            myapp-container=$IMAGE \
            --record
          kubectl rollout status deployment/myapp-deployment

      - name: Apply other Kubernetes manifests
        run: |
          kubectl apply -f k8s/